name: both  # Condition on bb preds and image feats 
top_k: 200  # The number of bbox predictions to use. -1 for all of them.
method: roi  # The method to condition on image feats. ['roi', 'seq' (DETR-style), 'both'] 
